databases:
  - name: smartdocdb
    plan: free
    databaseName: smartdoc
    user: smartdoc

services:
  - type: web
    plan: free
    name: smartdoc
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn smartdoc.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartdocdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4